version: 2.1

orbs:
  rust: circleci/rust@1.6.0

jobs:
  build-job:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.large
    steps:  
      - checkout
      - run: cargo --version
      - run:
          name: Run Tests
          command: "cargo test"



workflows:
  wasm-opt-rs-workflow:
    jobs:
      - build-job