version: 2.1

orbs:
  rust: circleci/rust@1.6.0

jobs:
  build-job:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.large
    steps:  
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run: cargo build --verbose
      - run: cargo test -- --nocapture
      - run: cargo fmt --check

workflows:
  wasm-opt-rs-workflow:
    jobs:
      - build-job