version: 2.1

orbs:
  rust: circleci/rust@1.6.0

jobs:
  build-test-job:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.large
    steps:  
      - checkout
      - run: git submodule update --init --recursive
      - rust/install
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - rust/test


workflows:
  wasm-opt-rs-workflow:
    jobs:
      - build-test-job
