jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.large
    steps:      
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - uses: actions/checkout@v3
      - run: git submodule update --init --recursive
      - run: cargo build --verbose
      - run: cargo test -- --nocapture